language: android
before_install:
- nvm install 6
- node --version
install:
- npm install
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script:
- npm run ci
- '[ -z "$TRAVIS_TAG" ] || (cd android && ./gradlew assembleRelease -PdisablePreDex)'
